### ISSUE TITLE
[Request] Comment Groups

### ISSUE THREAD

**Issue by Trofaaa** [mattwright324/youtube-comment-suite#15]
Hey Matt,

It would be super helpful if there was any possibility of you being able to please add an option to categorize (or group) the comments individually or on bulk selection? Ideally so I could click a bunch of comments (on the 'Search Comments' tab), then select a custom group to move them to. 
Then an option on the 'Search Comment's tab' to only search certain groups (the custom ones, plus any not categorized) i.e. so I can only display comments which aren't yet categorized. 

You've done an incredible job on this! :)
Thanks!

**Comment by mattwright324** [comment]
This is an interesting idea and not something I had thought of before. Adding comments to _Groups_ might make things too complicated but I could see value in tagging or categorizing comments and providing an option in the comment search options to filter on tag(s)/category. Allowing you to use tags might be more useful as you can tag a comment with more than one thing while a category would only be one thing. I'm not sure if the tag should be tied to the group specifically it was created under when searching or globally for all groups.

I have not heard of the flagger program before. It appears to be primarily about videos based on the description but I could see the value in using this tool for flagging comments! I can look into adding this in somehow.

**Comment by Flashtrax** [comment]
Yes, tagging as you've suggested would be perfect, ideally being able bulk tag on selection as you're going through a list.

I think whichever is easiest to be honest re: whether it should be tied to the group or globally. I'd probably think it would be better to have tags apply globally however. 

Thanks very much

**Comment by SiliconWafer** [comment]
Building on that idea, it could be great to be able to tag comments for bulk reply. For example, I recently posted a video that I did a particularly good job editing. It was notable, because my work is typically unedited, and the video has received ~100+ comments complimenting me on the editing. A couple of hours ago I took it upon myself to write back to some of those comments and say thank you. It would have been a godsend to be able to search that video's comments for "editing," select all of the relevant comments, and write a generic "Thanks! I'm glad that you liked it!"

I realize that one possible objection could be that bulk replies would facilitate spamming. A possible mitigant: to enable that feature you must be using your own API key.

Thank you!

**Comment by John9593** [comment]
Categorization would be helpful, is this difficult to implement?

**Comment by mattwright324** [comment]
I have a version of this out in the `develop` branch allowing you to add/remove tags on comments and use them in the comment search. It still needs some revision but will be out in the next release. As for bulk-reply, I too have the concern that it would facilitate spamming so will hold off on that functionality for now.
