### ISSUE TITLE
How to use this software?

### ISSUE THREAD

**Issue by ThomasKundera** [mattwright324/youtube-comment-suite#2]
Hi,

Thanks for publishing this code that I may find very useful if I know how to use it :-)

My first question is: how to build this code? I downloaded the java source code, but can see any build instructions.

Thanks.

**Comment by mattwright324** [comment]
Hi ThomasKundera,

In order to build the required libraries/dependencies include [mattwright/youtube-data-list](https://github.com/mattwright324/youtube-data-list), [jhy/jsoup](https://github.com/jhy/jsoup), [xerial/sqlite-jdbc](https://github.com/xerial/sqlite-jdbc), [google/gson](https://github.com/google/gson) and [Apache Commons Lang](https://commons.apache.org/proper/commons-lang/). The latest version of these should work just fine. The dependencies are linked in a `lib/` folder beside the compiled jar.

For reference the MANIFEST should show something like:

```
Manifest-Version: 1.0
Class-Path: . lib/gson-2.8.0.jar lib/commons-lang3-3.6.jar lib/jsoup-1
 .9.2.jar lib/sqlite-jdbc-3.19.3.jar lib/youtube-data-list-v1.1.5.jar
Main-Class: mattw.youtube.commentsuite.CommentSuite
```

However, to skip having to build manually you can also download the compiled jar with dependencies in the `youtube-comment-suite-v1.3.0.zip` on the [latest release](https://github.com/mattwright324/youtube-comment-suite/releases/tag/v1.3.0).

If you need more information please let me know.

Matt

**Comment by mattwright324** [comment]
Revisiting this question, I've recently added Maven framework support to this and dependency project [youtube-data-list](https://github.com/mattwright324/youtube-data-list) which should make building the project much easier. I still don't have clear build instructions written other than to pull down `youtube-data-list` and letting your IDE download the Maven dependencies, as I learn more about Maven maybe I can document something in the wiki.

**Comment by mattwright324** [comment]
In the last release, I eliminated the `youtube-data-list` custom project dependency. I also have the [Overview of the interface](https://github.com/mattwright324/youtube-comment-suite/wiki/Overview-of-the-interface) wiki page to briefly walk through what everything does and looks like.

Building/running should be straightforward in an IDE that supports Maven as now all dependencies can be downloaded easily with Maven. I'm not sure if building via IDE was the intended purpose of this question but I will close it for now. If I misinterpreted, let me know.
