### ISSUE TITLE
there is no  youtube-comment-suite.jar file in zip

### ISSUE THREAD

**Issue by azhar5678** [mattwright324/youtube-comment-suite#33]
there is no  youtube-comment-suite.jar file in zip

**Comment by mattwright324** [comment]
There should be... what OS and anti virus are you using? I could maybe see an overactive AV inspecting the zip and deleting it.

**Comment by pologlobal** [comment]
I agree with azhar because the file isn't available as well in the directory you have here in github.
I really look forward to use this so please help !

**Comment by mattwright324** [comment]
I just download the zip and see the jar. Same question, what OS and AV are you using?

**Comment by pologlobal** [comment]
I'm using windows. Just note that i don't have any programing experience and i'm a one click type of person haha.

**Comment by mattwright324** [comment]
Alright, windows 10? And are you using an anti virus (Windows Defender, Norton, McAfee, AVG, etc.)?

**Comment by pologlobal** [comment]
windows 8 
no i don't have any anti to be honest XD

**Comment by mattwright324** [comment]
Strange, I'd expect that to be the culprit. What are you using to view/unzip the zip file? Could you provide some screenshots?

**Comment by pologlobal** [comment]
Sure, But as you know inside the winrar you should be seeing the file but it's not there as well. 
![Screenshot_1](https://user-images.githubusercontent.com/58043340/69431672-dfadd180-0d40-11ea-8025-6a4be42ac007.png)

**Comment by mattwright324** [comment]
Ok, I see what is happening. I think you are downloading the wrong thing, that is the source code and not the compiled jar + dependencies which is why you aren't seeing the jar. When you're on the [Releases](https://github.com/mattwright324/youtube-comment-suite/releases) section click on `youtube-comment-suite-v1.4.2.zip` to download the correct zip as highlighted below. It seems you just downloaded the source code; I assume the original issue poster did the same thing.

![image](https://user-images.githubusercontent.com/7717432/69431998-cc7e1000-0d06-11ea-9e5f-75d89a7e02c8.png)

**Comment by pologlobal** [comment]
Aaaand it worked :D !!...thank you sir !

![Screenshot_1](https://user-images.githubusercontent.com/58043340/69433987-5e0c7280-0d45-11ea-9655-b3688883b5f1.png)

**Comment by mattwright324** [comment]
Great! I'll close this for now. If it doesn't apply to the original poster when they look at this it could be reopened if they provide details specific to their situation.

**Comment by azhar5678** [comment]
will it work for java 7, i found the jar

**Comment by mattwright324** [comment]
It will not work with Java 7, I recommend [upgrading to Java 8](https://www.java.com/en/download/).
