### ISSUE TITLE
Blacklist deleted channels and videos with comments disabled

### ISSUE THREAD

**Issue by bpo5r5** [mattwright324/youtube-comment-suite#43]
Would it be possible to add a blacklist feature for:
- Channels that have been deleted
- Videos with comments disabled

Having this feature would lower the amount of needless API calls.

Thanks!

**Comment by mattwright324** [comment]
While this does sound like a good idea, the problem is that those states are not always permanent. Channels are able to be reinstated. Videos with disabled comments could have them re-enabled -- some can be automatically disabled by YouTube and the author wants to undo that. There would be no way to tell if a channel or video had their state changed unless I query for them.
