### ISSUE TITLE
[BUG] Getting 403 Forbidden Error

### ISSUE THREAD

**Issue by Kajmce666** [mattwright324/youtube-comment-suite#53]
Doesn't work. Tried adding a video to the group (this one: https://www.youtube.com/watch?v=SKricIeeru0), but I get a 403 Access Denied error, stating: "quotaExceeded".
I tried it with other videos. No luck as well. Very disappointing.

**Comment by mattwright324** [comment]
Hi @Kajmce666,

This is because of the API quota limit, it appears that the quota limit has been exceeded for the day.

![image](https://user-images.githubusercontent.com/7717432/92504432-a6abf400-f1d0-11ea-8500-b6ed5183e756.png)

The limit is 1 million units per day. My default API key I have included in the app is being used by all others who have downloaded the tool too - the more using it in a day the quicker and more often this error will occur. More detail can be found here on issue [#5 YouTube API Quotas](5). It is possible to create and use your own key in the app which is also noted in that issue page.
