### ISSUE TITLE
How do I migrate my old groups and comments to the new release?

### ISSUE THREAD

**Issue by bdavisonhelo** [mattwright324/youtube-comment-suite#55]
I tried moving various configurations of files (including the sqlite db) over from my current working copy, but my groups are still not appearing. Thanks!

**Comment by mattwright324** [comment]
Hey @bdavisonhelo,

Which version are you migrating from?

**Comment by bdavisonhelo** [comment]
I'm not quite sure how to tell, but this may help. The folder name, which I don't think I changed since downloading it, is "youtube-comment-suite-v1.4-1.0."

Also, I'm new to Github and have a quick 'how to' question. There is another URL structure the should be accepted as a valid channel URL in YCS. 

-Is that something I should open an issue about?
-If so, am I correct in assuming that it should be its own issue, and not simply mentioned here?

I really appreciate your work on YCS and want to give feedback in whichever way will be most helpful. Thanks!

**Comment by mattwright324** [comment]
You can tell the version for sure by clicking on the gear icon in the top right corner of the app to open the settings menu then scrolling down. The version of the jar is at the bottom of the settings in the **About** section. In the new release version you tried copying files over to, if you open the logs folder and check the log file with the date of the day you tried it, do you see any errors or exceptions and share if you do?

Generally you are able to just copy the files `commentsuite.sqlite3` and `commentsuite.json` from an old release to the new release and it should bring over any settings and group items/data/videos/etc.

You could open a new issue about the channel URL thing. However, is it custom `/c/` URL? I had opened an issue with another of my YouTube projects why I couldn't support that URL pattern because the YouTube API doesn't have any support to query for it -- [youtube-metadata #1 channel custom url unsupported](https://github.com/mattwright324/youtube-metadata/issues/1).

**Comment by mattwright324** [comment]
I created a wiki page for this [Upgrade to a new release](https://github.com/mattwright324/youtube-comment-suite/wiki/Upgrade-to-a-new-release)
