### ISSUE TITLE
JSON files being saved in local encoding of Windows OS, not in UTF-8

### ISSUE THREAD

**Issue by iyutr** [mattwright324/youtube-comment-suite#61]
Windows 7 x86, Java 8.261.
All files are saved in my locale's encoding, so all latin-like letters with diacritics and all greek/georgian etc. letters become question marks, this is definitely a problem that needs to be addressed. In current state the program is useless. Please solve the issue, so that JSON files are always be saved in UTF-8. Thank you in advance.

**Comment by mattwright324** [comment]
@iyuter what version of the app are you using?

I thought I fixed this from issue #13 in release v1.4.2. Exported JSON files should be written in UTF-8

https://github.com/mattwright324/youtube-comment-suite/blob/aeabc826d72c833a279c8cf16ec63037e9422b5c/src/main/java/io/mattw/youtube/commentsuite/fxml/SCExportModal.java#L146

If you are using 1.4.2 or 1.4.3 then I guess this isn't worked as I expected it to.

**Comment by mattwright324** [comment]
Though, now I think I see the issue. I don't have that same UTF-8 for all the file writers.

**Comment by iyuter** [comment]
mattwright324, 
sorry, I am not a programmer, a file
youtube-comment-suite-1.4.3.jar\io\mattw\youtube\commentsuite\fxml\SCExportModal.class
is a compiled binary, I don't know how to change it. Could you please send me a link to this file ("SCExportModal.class") with the above-mentioned changes, or to the complete archive "youtube-comment-suite-1.4.3.jar"?

**Comment by Rupthya** [comment]
I have same issue with 1.4.3, but just think i reply at a wrong issue (closed) : https://github.com/mattwright324/youtube-comment-suite/issues/24

**Comment by mattwright324** [comment]
I have this fixed out in commit 9697b35d534fb699e6432e45a9665ac00c0b2f3b in the [develop branch](https://github.com/mattwright324/youtube-comment-suite/tree/develop) and will be out in the next release.

However, instead of waiting, also in the develop branch I have recently written [BUILD.md](https://github.com/mattwright324/youtube-comment-suite/blob/develop/BUILD.md) to assist with building the project from source. If you clone the project, switch to the `develop` branch, and follow the guide you should be able to use it early.

**Comment by iyutr** [comment]
I confirm, it now saves properly, thank you very much !!!

**Comment by Rupthya** [comment]
Thank you Matthew, Working properly now.
