### ISSUE TITLE
Sorting results by views causes no results to be returned

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#70]
Sorting results by views causes the application to not return any. Other types of sorting seem to work fine.
![searchsort](https://user-images.githubusercontent.com/36137483/104073257-13a4ba00-51c2-11eb-9a40-ad074b31bbc4.PNG)

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by mattwright324** [comment]
This seems to be because I am sending to the YouTube API order param `views` instead of the actual value it should be `viewCount`. Looking at the API docs I can also add a new option `videoCount` too. 

I have this fixed/added in a commit to the develop branch 2e4f25c060416ea9d4c8d7144920b379bfd41112 and will be in the next release.
