### ISSUE TITLE
It is possible to remove existing group's name

### ISSUE THREAD

**Issue by kacper1112** [mattwright324/youtube-comment-suite#71]
While editing group's name it is possible to enter no characters, and the new 'name' will be accepted.
![emptynameagterchange](https://user-images.githubusercontent.com/36137483/104633794-898ea280-5654-11eb-9e90-49416073959e.PNG)
In other parts of the application, the group selection list still shows the old name. After switching to the group though, the name is displayed as empty.
![empty_name_list](https://user-images.githubusercontent.com/36137483/104633950-c6f33000-5654-11eb-898b-55dffe9a3139.PNG)

The group selection list problem is probably connected to #66 

Platform: Windows 10
Java: 1.8.0_271 (Oracle)

Ran both using the release 1.4.3 jar file and compiled from source myself.

**Comment by kacper1112** [comment]
It is also possible to create a new group containing only whitespace, eg 3 spaces is a valid group name. It also means that "group" is different than "group ".

**Comment by mattwright324** [comment]
Thanks @kacper1112 

I have this fixed in the `develop` branch and will be out in the next release.
- Replaced the X with a floppy symbol to save. The X is now actually to cancel the rename.
- Disables the save button when input is empty. Input is trimmed so can't add spaces before/after or have a just-spaces name.
