### ISSUE TITLE
"Search YouTube" results has duplicates

### ISSUE THREAD

**Issue by bernard01** [mattwright324/youtube-comment-suite#85]
With the number of results growing, say thousand results, a list copied to the clipboard contains many duplicates. With this size, typically 3 times as many results as the number of real hits. I don't know whether this is caused by the YouTube API of by YCS. Since YCS pagination works by combining pages into a larger result, I guess YCS could check for duplicates and sort again after reading the results from a set. The copy function is really great because I can paste the result into a spreadsheet and build my own SQL from the result and eliminate results that are already in the database.

**Comment by mattwright324** [comment]
This appears to be a [limitation on YouTube's side](https://stackoverflow.com/a/27526563/2650847) that I did not account for, at about 10-13 pages in the API nextPageToken reverts back to blank which is the first page. So you can only get ~500-650 results. Since the app doesn't stop you and you get into the 1500 range you would then be seeing the duplicate entries since it looped back to the first API page 2-3 times.

I can disable the next page token when it returns blank but is not the first search.

**Comment by mattwright324** [comment]
I have this fixed in commit 3af47e939f7e8017187ea1d37d71d32caa7bb4dc and will be out in the next release.

When it reaches the last page of results that the API is willing to provide the button will display as "Out of pages" and the total will be replaced with the total of displayed results to avoid confusion.

![image](https://user-images.githubusercontent.com/7717432/127936815-a2c0a356-4566-4059-aa89-4b69221b543a.png)
![image](https://user-images.githubusercontent.com/7717432/127936798-b8ca95b9-cb4b-4468-ba60-6ef6a6a30b8e.png)
